<?php namespace Godstorm\Contributor\Components;

use Cms\Classes\ComponentBase;
use GodStorm\Contributor\Models\Contributor as ContributorModel;

class Contributor extends ComponentBase
{
    /**
     * A collection of posts to display
     * @var Collection
     */
    public $contributors;

    public function componentDetails()
    {
        return [
            'name'        => 'contributor Component',
            'description' => 'No description provided yet...'
        ];
    }

    public function defineProperties()
    {
        return [];
    }

    public function onRun()
    {
//        parent::onRun(); // TODO: Change the autogenerated stub
        $this->contributors = $this->page['contributors'] = $this->listContributors();
    }

    protected function listContributors()
    {
        $contributors = ContributorModel::all();
        return $contributors;
    }
}
